spring:
  datasource:
    url: jdbc:h2:mem:fileUploadDownload
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    h2:
      console:
        enables: true

fileRepositoryFolder: C:\Users\Manuel\Desktop\DEVELHOPE\Spring Advance\FileRepository
